/**
 * @context  Core layer — type generator at src/core/type-generator.ts
 * @does     Converts CollectionSchema definitions into TypeScript declaration strings for .d.ts output
 * @depends  src/shared/fields.ts
 * @do       Add new field-to-type mappings here as new field types are introduced
 * @dont     Import from CLI or UI; access the filesystem; perform I/O
 */

import type { FieldDefinition, CollectionSchema } from "../shared/fields.js";

function indent(code: string, spaces = 2): string {
  return code
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : " ".repeat(spaces) + line))
    .join("\n");
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase());
}

function fieldToTsType(field: FieldDefinition): string {
  switch (field.type) {
    case "text":
    case "long-text":
      return "string";

    case "email":
      return "Email";

    case "url":
      return "HttpUrl";

    case "media":
      return "MediaPath";

    case "id":
      return "ID";

    case "slug":
      return "Slug";

    case "date":
      return field.includeTime ? "Date" : "ISODate";

    case "created-time":
    case "updated-time":
      return "Date";

    case "number":
      return "number";

    case "boolean":
      return "boolean";

    case "select":
    case "status": {
      const values = field.options.map((o) => JSON.stringify(o.value));
      return values.length > 0 ? values.join(" | ") : "string";
    }

    case "multi-select": {
      const values = field.options.map((o) => JSON.stringify(o.value));
      const union = values.length > 0 ? values.join(" | ") : "string";
      return `Array<${union}>`;
    }

    case "object":
      return generateObjectType(field.fields);

    case "array":
      return `Array<${generateObjectType(field.itemFields)}>`;

    case "relation":
      return field.multiple === true ? "ID[]" : "ID";

    case "formula":
      if (field.resultType === "number") return "number";
      if (field.resultType === "boolean") return "boolean";
      return "string";

    default:
      return "unknown";
  }
}

function generateObjectType(fields: FieldDefinition[]): string {
  if (fields.length === 0) return "Record<string, unknown>";

  const lines = fields.map((field) => {
    const optional = field.required === false ? "?" : "";
    const tsType = fieldToTsType(field);
    const comment = field.description ? `/** ${field.description} */\n` : "";
    return `${comment}${field.name}${optional}: ${tsType};`;
  });

  return `{\n${indent(lines.join("\n"))}\n}`;
}

export function generateInterfaceForSchema(schema: CollectionSchema): string {
  const name = toPascalCase(schema.collection) + "Entry";
  const label = schema.label ?? schema.collection;
  const body = generateObjectType(schema.fields);
  return `/** Data shape for the "${label}" collection. */\nexport interface ${name} ${body}`;
}

/**
 * Generate a complete TypeScript declaration file for all provided schemas.
 *
 * @example
 * ```ts
 * const code = generateCollectionTypes([blogSchema, authorSchema]);
 * await fs.writeFile(".studio/types.d.ts", code, "utf-8");
 * ```
 */
export function generateCollectionTypes(schemas: CollectionSchema[]): string {
  const banner = [
    "// This file is auto-generated by nextjs-studio.",
    "// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.",
    "",
    "// Branded scalar types — structurally strings/numbers but semantically distinct.",
    "declare const __brand: unique symbol;",
    "type Brand<T, B extends string> = T & { readonly [__brand]: B };",
    "",
    "export type Email     = Brand<string, 'Email'>;",
    "export type HttpUrl   = Brand<string, 'HttpUrl'>;",
    "export type ISODate   = Brand<string, 'ISODate'>;",
    "export type MediaPath = Brand<string, 'MediaPath'>;",
    "export type ID        = Brand<string, 'ID'>;",
    "export type Slug      = Brand<string, 'Slug'>;",
  ].join("\n");

  const interfaces = schemas.map(generateInterfaceForSchema).join("\n\n");

  const collectionRegistry = [
    "// Augment both entry points so queryCollection() is fully typed regardless of import path.",
    "declare module 'nextjs-studio' {",
    "  interface CollectionTypeMap {",
    schemas.map((schema) => `    ${JSON.stringify(schema.collection)}: ${toPascalCase(schema.collection)}Entry;`).join("\n"),
    "  }",
    "}",
    "declare module 'nextjs-studio/server' {",
    "  interface CollectionTypeMap {",
    schemas.map((schema) => `    ${JSON.stringify(schema.collection)}: ${toPascalCase(schema.collection)}Entry;`).join("\n"),
    "  }",
    "}",
  ].join("\n");

  return [banner, interfaces, collectionRegistry].join("\n\n") + "\n";
}
