/**
 * Type generator — converts CollectionSchema definitions into TypeScript
 * declaration strings that can be written to a `.d.ts` file.
 *
 * Generated types are consumed by the user's Next.js project so that
 * `queryCollection("blog").all()` returns fully-typed entries.
 */

import type {
  FieldDefinition,
  CollectionSchema,
  FormulaField,
} from "../shared/fields.js";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function indent(code: string, spaces = 2): string {
  return code
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : " ".repeat(spaces) + line))
    .join("\n");
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Field → TypeScript type string
// ---------------------------------------------------------------------------

function fieldToTsType(field: FieldDefinition): string {
  switch (field.type) {
    // Plain text — no semantic constraint
    case "text":
    case "long-text":
      return "string";

    case "email":
      return "Email";

    case "url":
      return "HttpUrl";

    case "media":
      return "MediaPath";

    case "id":
      return "ID";

    case "slug":
      return "Slug";

    case "date":
      return field.includeTime ? "Date" : "ISODate";

    case "created-time":
    case "updated-time":
      return "Date";

    case "number":
      return "number";

    case "boolean":
      return "boolean";

    case "select":
    case "status": {
      const values = field.options.map((o) => JSON.stringify(o.value));
      return values.length > 0 ? values.join(" | ") : "string";
    }

    case "multi-select": {
      const values = field.options.map((o) => JSON.stringify(o.value));
      const union = values.length > 0 ? values.join(" | ") : "string";
      return `Array<${union}>`;
    }

    case "object":
      return generateObjectType(field.fields);

    case "array":
      return `Array<${generateObjectType(field.itemFields)}>`;

    case "relation":
      return field.multiple === true ? "ID[]" : "ID";

    case "formula": {
      const f = field as FormulaField;
      if (f.resultType === "number") return "number";
      if (f.resultType === "boolean") return "boolean";
      return "string";
    }

    default:
      return "unknown";
  }
}

function generateObjectType(fields: FieldDefinition[]): string {
  if (fields.length === 0) return "Record<string, unknown>";

  const lines = fields.map((f) => {
    const optional = f.required === false ? "?" : "";
    const tsType = fieldToTsType(f);
    const comment = f.description ? `/** ${f.description} */\n` : "";
    return `${comment}${f.name}${optional}: ${tsType};`;
  });

  return `{\n${indent(lines.join("\n"))}\n}`;
}

// ---------------------------------------------------------------------------
// Schema → interface declaration
// ---------------------------------------------------------------------------

export function generateInterfaceForSchema(schema: CollectionSchema): string {
  const name = toPascalCase(schema.collection) + "Entry";
  const label = schema.label ?? schema.collection;
  const body = generateObjectType(schema.fields);

  return `/** Data shape for the "${label}" collection. */\nexport interface ${name} ${body}`;
}

// ---------------------------------------------------------------------------
// Multiple schemas → full .d.ts file
// ---------------------------------------------------------------------------

/**
 * Generate a complete TypeScript declaration file for all provided schemas.
 *
 * @example
 * ```ts
 * const code = generateCollectionTypes([blogSchema, authorSchema]);
 * await fs.writeFile(".studio/types.d.ts", code, "utf-8");
 * ```
 */
export function generateCollectionTypes(schemas: CollectionSchema[]): string {
  const banner = [
    "// This file is auto-generated by nextjs-studio.",
    "// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.",
    "",
    "// Branded scalar types — structurally strings/numbers but semantically distinct.",
    "declare const __brand: unique symbol;",
    "type Brand<T, B extends string> = T & { readonly [__brand]: B };",
    "",
    "export type Email     = Brand<string, 'Email'>;",
    "export type HttpUrl   = Brand<string, 'HttpUrl'>;",
    "export type ISODate   = Brand<string, 'ISODate'>;",
    "export type MediaPath = Brand<string, 'MediaPath'>;",
    "export type ID        = Brand<string, 'ID'>;",
    "export type Slug      = Brand<string, 'Slug'>;",
  ].join("\n");

  const interfaces = schemas.map(generateInterfaceForSchema).join("\n\n");

  const collectionMap = schemas
    .map((s) => {
      const name = toPascalCase(s.collection) + "Entry";
      return `  ${JSON.stringify(s.collection)}: ${name};`;
    })
    .join("\n");

  const collectionRegistry = [
    "/** Maps collection names to their entry types for use with `queryCollection()`. */",
    "export interface CollectionTypeMap {",
    collectionMap,
    "}",
  ].join("\n");

  return [banner, interfaces, collectionRegistry].join("\n\n") + "\n";
}
